version: "3.0"
services:
  acng:
    container_name: cache.lab.com
    image: apt-cacher-ng:ubuntu-20-04
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/var/cache/apt-cacher-ng:rw
    logging:
        driver: "json-file"
        options:
            max-size: "1m"